#!/bin/bash

# =============================================================================
# Second-Level LSS SLURM Job Launcher (Trial Merging)
# =============================================================================
#
# This script launches SLURM jobs for the second step of LSS analysis:
# merging individual LSS trial outputs into 4D NIfTI images.
# It automatically detects and launches scripts generated by create_1st_LSS_2_cateAlltrials.py
#
# Usage:
#   ./launch_1st_LSS_2nd.sh                    # Launch all available scripts
#   ./launch_1st_LSS_2nd.sh --task phase2     # Launch only phase2 scripts
#   ./launch_1st_LSS_2nd.sh --subjects N101 N102 # Launch only specific subjects
#   ./launch_1st_LSS_2nd.sh --dry-run          # Show what would be launched
#   ./launch_1st_LSS_2nd.sh --help             # Show this help message
#
# =============================================================================

# =============================================================================
# CONFIGURATION
# =============================================================================

# Base directory for LSS step 2 scripts
SCRIPTS_BASE_DIR="/gscratch/scrubbed/fanglab/xiaoqian/NARSAD/work_flows/Lss_step2"

# Default settings
TASK=""
SUBJECTS=()
DRY_RUN=false
VERBOSE=false

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

show_usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Launch SLURM jobs for LSS trial merging (Step 2 of LSS analysis).

This step merges individual LSS trial outputs (cope1 files) into 4D NIfTI images
for each subject-task-contrast combination.

OPTIONS:
    --task TASK             Specific task to process (phase2, phase3)
    --subjects SUB1 SUB2    Specific subjects to process
    --dry-run               Show what would be launched without submitting
    --verbose               Verbose output
    --help                  Show this help message

EXAMPLES:
    # Launch all available scripts
    $0
    
    # Launch only phase2 scripts
    $0 --task phase2
    
    # Launch only specific subjects
    $0 --subjects N101 N102 N103
    
    # Launch phase2 scripts for specific subjects
    $0 --task phase2 --subjects N101 N102
    
    # Show what would be launched without submitting
    $0 --dry-run
    
    # Verbose output
    $0 --verbose

WORKFLOW CONTEXT:
    This script is Step 2 of the LSS analysis pipeline:
    
    Step 1: create_1st_LSS.py -> run_1st_LSS.py (individual trial GLM)
    Step 2: create_1st_LSS_2_cateAlltrials.py -> first_LSS_2_cateAlltrials.py (merge trials)
    Step 3: Similarity analysis and group-level processing
    
    The scripts generated by create_1st_LSS_2_cateAlltrials.py are located in:
    $SCRIPTS_BASE_DIR/{task}/sub_{subject}_slurm.sh

EOF
}

# =============================================================================
# ARGUMENT PARSING
# =============================================================================

while [[ $# -gt 0 ]]; do
    case $1 in
        --task)
            TASK="$2"
            shift 2
            ;;
        --subjects)
            shift
            while [[ $# -gt 0 && ! "$1" =~ ^-- ]]; do
                SUBJECTS+=("$1")
                shift
            done
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --verbose)
            VERBOSE=true
            shift
            ;;
        --help)
            show_usage
            exit 0
            ;;
        *)
            echo "Error: Unknown option: $1" >&2
            show_usage
            exit 1
            ;;
    esac
done

# =============================================================================
# SCRIPT DISCOVERY AND LAUNCHING
# =============================================================================

echo "=========================================="
echo "Second-Level LSS SLURM Job Launcher"
echo "LSS Trial Merging (Step 2)"
echo "=========================================="

if [[ -n "$TASK" ]]; then
    echo "Task filter: $TASK"
fi

if [[ ${#SUBJECTS[@]} -gt 0 ]]; then
    echo "Subject filter: ${SUBJECTS[*]}"
fi

if [[ "$DRY_RUN" == true ]]; then
    echo "DRY RUN MODE - No jobs will be submitted"
fi

if [[ "$VERBOSE" == true ]]; then
    echo "Verbose mode enabled"
fi

echo "=========================================="

# Function to launch scripts from a specific task directory
launch_task_scripts() {
    local task_dir="$1"
    local task_name="$2"
    
    if [[ ! -d "$task_dir" ]]; then
        echo "Task directory not found: $task_dir"
        return
    fi
    
    echo "Processing task: $task_name"
    echo "Scanning directory: $task_dir"
    
    # Find all SLURM scripts in the task directory
    local scripts_found=0
    local scripts_launched=0
    
    # Get all SLURM scripts
    local all_scripts=()
    while IFS= read -r -d '' script; do
        all_scripts+=("$script")
    done < <(find "$task_dir" -name "*.sh" -type f -print0)
    
    if [[ ${#all_scripts[@]} -eq 0 ]]; then
        echo "  No SLURM scripts found in: $task_dir"
        return
    fi
    
    echo "  Found ${#all_scripts[@]} SLURM scripts"
    
    # Process each script
    for script in "${all_scripts[@]}"; do
        local script_name=$(basename "$script")
        
        # Apply subject filter if specified
        local should_launch=true
        
        if [[ ${#SUBJECTS[@]} -gt 0 ]]; then
            should_launch=false
            for subject in "${SUBJECTS[@]}"; do
                if [[ "$script_name" =~ $subject ]]; then
                    should_launch=true
                    break
                fi
            done
        fi
        
        if [[ "$should_launch" == true ]]; then
            scripts_found=$((scripts_found + 1))
            
            if [[ "$DRY_RUN" == true ]]; then
                echo "    [DRY RUN] Would submit: $script_name"
            else
                if [[ "$VERBOSE" == true ]]; then
                    echo "    Submitting: $script_name"
                fi
                
                # Submit the job
                local job_id=$(sbatch "$script" 2>&1)
                
                if [[ $? -eq 0 ]]; then
                    # Extract job ID from sbatch output
                    local job_number=$(echo "$job_id" | grep -o '[0-9]\+' | head -1)
                    if [[ -n "$job_number" ]]; then
                        echo "    Submitted: $script_name (Job ID: $job_number)"
                    else
                        echo "    Submitted: $script_name"
                    fi
                    scripts_launched=$((scripts_launched + 1))
                else
                    echo "    Error submitting: $script_name - $job_id"
                fi
            fi
        fi
    done
    
    if [[ "$DRY_RUN" == true ]]; then
        echo "  [DRY RUN] Found $scripts_found scripts (would launch $scripts_found)"
    else
        echo "  Found $scripts_found scripts, launched $scripts_launched"
    fi
    
    echo ""
}

# =============================================================================
# MAIN EXECUTION
# =============================================================================

# Determine which tasks to process
if [[ -n "$TASK" ]]; then
    # Process only specified task
    if [[ "$TASK" == "phase2" || "$TASK" == "phase3" ]]; then
        task_dir="$SCRIPTS_BASE_DIR/$TASK"
        launch_task_scripts "$task_dir" "$TASK"
    else
        echo "Error: Invalid task '$TASK'. Valid tasks are: phase2, phase3"
        exit 1
    fi
else
    # Process all available tasks
    for task in "phase2" "phase3"; do
        task_dir="$SCRIPTS_BASE_DIR/$task"
        if [[ -d "$task_dir" ]]; then
            launch_task_scripts "$task_dir" "$task"
        else
            echo "Task directory not found: $task_dir"
        fi
    done
fi

# =============================================================================
# SUMMARY
# =============================================================================

echo "=========================================="
echo "Job launching completed!"
echo "=========================================="

if [[ "$DRY_RUN" == true ]]; then
    echo ""
    echo "To actually launch the jobs, run without --dry-run:"
    cmd="$0"
    [[ -n "$TASK" ]] && cmd="$cmd --task $TASK"
    [[ ${#SUBJECTS[@]} -gt 0 ]] && cmd="$cmd --subjects ${SUBJECTS[*]}"
    echo "  $cmd"
fi

echo ""
echo "LSS Analysis Pipeline Status:"
echo "  Step 1: First-level LSS analysis (individual trials)"
echo "    - Scripts: create_1st_LSS.py"
echo "    - Launcher: launch_1st_LSS_1st.sh"
echo ""
echo "  Step 2: Trial merging (4D image creation) [CURRENT STEP]"
echo "    - Scripts: create_1st_LSS_2_cateAlltrials.py"
echo "    - Launcher: launch_1st_LSS_2nd.sh [THIS SCRIPT]"
echo ""
echo "  Step 3: Similarity analysis and group processing"
echo "    - Scripts: Various similarity analysis scripts"
echo "    - Launcher: launch_group_LSS.sh"
echo ""
echo "To check job status, use:"
echo "  squeue -u \$USER"
echo ""
echo "To check specific job output:"
echo "  tail -f /path/to/sub_{subject}_%j.out"
echo ""
echo "Next steps after trial merging:"
echo "  1. Wait for all jobs to complete"
echo "  2. Verify 4D images were created successfully"
echo "  3. Proceed to Step 3 (similarity analysis)"
echo "=========================================="
