#!/bin/bash

# =============================================================================
# LSS Similarity Analysis Job Launcher (Step 3)
# =============================================================================
#
# This script launches SLURM jobs for LSS similarity analysis (Step 3).
# It automatically detects and launches scripts generated by create_1st_LSS_3rd_similarity.py
#
# Usage:
#   ./launch_1st_LSS_3rd_similarity.sh                    # Launch all available scripts
#   ./launch_1st_LSS_3rd_similarity.sh --dry-run          # Show what would be launched
#   ./launch_1st_LSS_3rd_similarity.sh --verbose          # Show detailed output
#
# Author: Xiaoqian Xiao (xiao.xiaoqian.320@gmail.com)
#
# =============================================================================

# =============================================================================
# CONFIGURATION
# =============================================================================

# Base directory for LSS step 3 scripts
SCRIPTS_BASE_DIR="/gscratch/scrubbed/fanglab/xiaoqian/NARSAD/work_flows/LSS_step3"

# Default settings
DRY_RUN=false
VERBOSE=false

# =============================================================================
# ARGUMENT PARSING
# =============================================================================

while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run|-n)
            DRY_RUN=true
            shift
            ;;
        --verbose|-v)
            VERBOSE=true
            shift
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "OPTIONS:"
            echo "  --dry-run, -n       Show what would be submitted without submitting"
            echo "  --verbose, -v       Show detailed output during submission"
            echo "  --help, -h          Show this help message"
            echo ""
            echo "EXAMPLES:"
            echo "  $0                                    # Submit all similarity analysis scripts"
            echo "  $0 --dry-run                         # Show what would be submitted"
            echo "  $0 --verbose                          # Show detailed output"
            echo ""
            echo "Workflow Context:"
            echo "  This script is Step 3 of the LSS analysis pipeline:"
            echo "  Step 1: First-level LSS analysis (individual trial GLM)"
            echo "  Step 2: Trial merging (4D image creation)"
            echo "  Step 3: Similarity analysis [THIS SCRIPT]"
            echo "  Step 4: Group-level analysis and statistical testing"
            exit 0
            ;;
        *)
            echo "Error: Unknown option: $1" >&2
            echo "Use --help for usage information" >&2
            exit 1
            ;;
    esac
done

# =============================================================================
# SCRIPT DISCOVERY AND LAUNCHING
# =============================================================================

echo "=========================================="
echo "LSS Similarity Analysis Job Launcher - Step 3 of LSS Pipeline"
echo "=========================================="
echo "Scripts directory: $SCRIPTS_BASE_DIR"

if [[ "$DRY_RUN" == true ]]; then
    echo "DRY RUN MODE - No jobs will be submitted"
fi

if [[ "$VERBOSE" == true ]]; then
    echo "VERBOSE MODE - Detailed output enabled"
fi

echo "=========================================="

# Check if scripts directory exists
if [[ ! -d "$SCRIPTS_BASE_DIR" ]]; then
    echo "Error: Scripts directory does not exist: $SCRIPTS_BASE_DIR"
    echo "Please run create_1st_LSS_3rd_similarity.py first to generate the scripts."
    exit 1
fi

# Submit all scripts in all subdirectories
total_scripts_submitted=0

for phase_dir in "$SCRIPTS_BASE_DIR"/*/; do
    if [[ -d "$phase_dir" ]]; then
        phase_name=$(basename "$phase_dir")
        echo "Processing phase: $phase_name"
        
        for analysis_dir in "$phase_dir"/*/; do
            if [[ -d "$analysis_dir" ]]; then
                analysis_type=$(basename "$analysis_dir")
                echo "  Processing analysis type: $analysis_type"
                
                # Submit all scripts in this directory
                scripts_found=0
                scripts_submitted=0
                
                for script in "$analysis_dir"/*.sh; do
                    if [[ -f "$script" ]]; then
                        scripts_found=$((scripts_found + 1))
                        script_name=$(basename "$script")
                        
                        if [[ "$DRY_RUN" == true ]]; then
                            echo "    [DRY RUN] Would submit: $script_name"
                            scripts_submitted=$((scripts_submitted + 1))
                            total_scripts_submitted=$((total_scripts_submitted + 1))
                        else
                            echo "    Submitting: $script_name"
                            if [[ "$VERBOSE" == true ]]; then
                                sbatch "$script"
                            else
                                sbatch "$script" > /dev/null 2>&1
                            fi
                            
                            if [[ $? -eq 0 ]]; then
                                scripts_submitted=$((scripts_submitted + 1))
                                total_scripts_submitted=$((total_scripts_submitted + 1))
                                if [[ "$VERBOSE" == true ]]; then
                                    echo "      ✓ Successfully submitted"
                                fi
                            else
                                echo "      ✗ Warning: Failed to submit $script_name"
                            fi
                        fi
                    fi
                done
                
                echo "    Summary: $scripts_submitted/$scripts_found scripts submitted"
                echo ""
            fi
        done
    fi
done

# Final summary
echo "=========================================="
echo "Job launching completed!"
echo "=========================================="

if [[ "$DRY_RUN" == true ]]; then
    echo "DRY RUN: Would have submitted $total_scripts_submitted scripts"
    echo ""
    echo "To actually submit the jobs, run without --dry-run"
else
    echo "Total scripts submitted: $total_scripts_submitted"
    echo ""
    echo "Use 'squeue -u $USER' to monitor job status"
    echo "Use 'scancel <job_id>' to cancel specific jobs"
fi

echo ""
echo "LSS Analysis Pipeline Status:"
echo "  Step 1: First-level LSS analysis (individual trials)"
echo "    - Scripts: create_1st_LSS_singleTrialEstimate.py"
echo "    - Launcher: launch_1st_LSS_1st_singleTrialEstimate.sh"
echo ""
echo "  Step 2: Trial merging (4D image creation)"
echo "    - Scripts: create_1st_LSS_2nd_cateAlltrials.py"
echo "    - Launcher: launch_1st_LSS_2nd_cateAlltrials.sh"
echo ""
echo "  Step 3: Similarity analysis [COMPLETED]"
echo "    - Scripts: create_1st_LSS_3rd_similarity.py"
echo "    - Launcher: launch_1st_LSS_3rd_similarity.sh [THIS SCRIPT]"
echo ""
echo "  Step 4: Group-level analysis and statistical testing"
echo "    - Ready for group-level analysis"
echo ""

if [[ "$DRY_RUN" == true ]]; then
    echo "Ready to submit jobs (run without --dry-run)"
else
    echo "The similarity analysis jobs are now running!"
fi

echo "=========================================="
